# Generated by Django 5.1.1 on 2024-09-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
