# Generated by Django 5.2.2 on 2025-07-02 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
