from enum import StrEnum


class FoodCategory(StrEnum):
    BEVERAGES = "Beverages"
    FRUITS = "Fruits"
    VEGETABLES = "Vegetables"
    GRAINS_AND_CEREALS = "Grains and Cereals"
    DAIRY_AND_ALTERNATIVES = "Dairy and Dairy Alternatives"
    MEAT_AND_POULTRY = "Meat and Poultry"
    FISH_AND_SEAFOOD = "Fish and Seafood"
    LEGUMES_AND_PULSES = "Legumes and Pulses"
    NUTS_AND_SEEDS = "Nuts and Seeds"
    HERBS_AND_SPICES = "Herbs and Spices"
    CONDIMENTS_AND_SAUCES = "Condiments and Sauces"
    SNACKS = "Snacks"
    DESSERTS_AND_SWEETS = "Desserts and Sweets"
    BAKED_GOODS = "Baked Goods"
    EGGS = "Eggs"
    OILS_AND_FATS = "Oils and Fats"
    PROCESSED_FOODS = "Processed Foods"
    FROZEN_FOODS = "Frozen Foods"
    CANNED_FOODS = "Canned Foods"
    ORGANIC_FOODS = "Organic Foods"
    GLUTEN_FREE_FOODS = "Gluten-Free Foods"
    VEGAN_VEGETARIAN_FOODS = "Vegan/Vegetarian Foods"
    FERMENTED_FOODS = "Fermented Foods"
    SUPERFOODS = "Superfoods"
    FUNCTIONAL_FOODS = "Functional Foods"
    BABY_FOOD = "Baby Food"
    PET_FOOD = "Pet Food"
    ALCOHOLIC_BEVERAGES = "Alcoholic Beverages"
    OTHER = "Other"
